#!/bin/bash

# Tested on SM-N910G Stock Firmware

#set -x
#set -v

export UNINSTALL="
com.facebook.katana
com.facebook.system
com.facebook.appmanager
flipboard.boxer.app
flipboard.app
tv.peel.smartremote
com.sec.android.widgetapp.samsungapps
com.sec.android.directshare
com.sec.android.widgetapp.easymodecontactswidget
com.sec.android.cloudagent.dropboxoobedummy
com.sec.android.widgetapp.tapandpay
com.sec.android.widgetapp.webmanual
com.android.printspooler
com.sec.app.samsungprintservice
com.sec.android.widgetapp.ap.hero.accuweather
com.sec.android.widgetapp.activeapplicationwidget
com.samsung.android.app.simplesharing
com.sec.allsharecastplayer
com.dropbox.android
com.samsung.android.app.vrsetupwizardstub
com.samsung.android.hmt.vrshell
com.samsung.android.hmt.vrsvc
com.samsung.android.app.mirrorlink
com.samsung.android.allshare.service.fileshare
com.evernote
com.monotype.android.font.cooljazz
com.samsung.android.allshare.service.mediashare
com.google.android.play.games
com.google.android.apps.magazines
com.google.android.videos
com.dsi.ant.service.socket
com.dsi.ant.sample.acquirechannels
com.dsi.ant.server
com.dsi.ant.plugins.antplus
com.sec.penup
com.sec.android.app.tourviewer
com.google.android.apps.plus
com.google.android.apps.books
com.google.android.music
com.google.android.talk
com.sec.android.app.billing
com.sec.android.app.easylauncher
com.google.android.feedback
com.monotype.android.font.chococooky
com.android.chrome
com.android.dreams.phototable
com.android.dreams.basic
com.google.android.apps.photos
com.sec.android.app.chromecustomizations
com.chrome.deviceextras.samsung
com.sec.android.app.music
com.google.android.gm
com.google.android.apps.docs
com.google.android.googlequicksearchbox
com.google.android.marvin.talkback
com.google.android.tts
com.sec.face
com.google.android.setupwizard
com.samsung.android.fingerprint.service
com.samsung.android.easysetup
com.monotype.android.font.rosemary
com.sec.di.SmartSelfShot
com.sec.android.app.samsungapps
com.samsung.android.smartface
com.samsung.android.app.pinboard
com.samsung.android.clipboarduiservice
com.sec.android.widgetapp.locationwidget
com.android.calllogbackup
com.lifevibes.trimapp
com.android.apps.tag
com.samsung.android.scloud.backup
com.samsung.android.mdm
com.samsung.android.scloud
com.samsung.android.nearby.mediaserver
com.samsung.android.app.watchmanagerstub
com.enhance.gameservice
com.android.email
com.sec.enterprise.knox.cloudmdm.smdms
com.samsung.android.sm.provider
com.android.exchange
com.samsung.aasaservice
com.samsung.android.sconnect
com.sec.android.easysettings
com.sec.android.app.sbrowser
com.google.android.youtube
com.sec.smartcard.manager
com.samsung.android.sm
com.sec.android.app.voicenote
com.samsung.android.app.withtv
com.vlingo.midas
com.samsung.android.keyguardwallpaperupdator
com.sec.android.app.interactivekeyguardtutorial
com.sec.android.automotive.drivelink
"

export DISABLE="
"

export IFS="
"

echo Uninstalling
for i in $UNINSTALL
do
	echo $i
	./adb.exe shell "pm uninstall --user 0 $i"
	./adb.exe shell "am force-stop --user 0 $i"
done

echo
echo Disabling and force stopping
for i in $DISABLE
do
	echo $i
	./adb.exe shell "pm disable-user --user 0 $i"
	./adb.exe shell "am force-stop --user 0 $i"
done

#
# List of stock firmware enabled packages for unbranded Note 4:
#

#com.sec.android.emergencylauncher
#com.samsung.android.dlp.service
#com.mobeam.barcodeService
#com.samsung.android.provider.filterprovider
#com.samsung.android.writingbuddyservice
#com.monotype.android.font.rosemary
#com.sec.android.app.DataCreate
#com.sec.android.providers.mapcon
#com.gd.mobicore.pa
#com.google.android.youtube
#com.samsung.android.app.galaxyfinder
#com.sec.android.app.chromecustomizations
#com.sec.android.app.ocrseg
#com.android.providers.telephony
#com.sec.android.app.parser
#com.sec.android.providers.iwlansettings
#com.google.android.googlequicksearchbox
#com.vlingo.midas
#com.android.providers.calendar
#com.osp.app.signin
#com.samsung.clipboardsaveservice
#com.sec.automation
#com.android.providers.media
#com.google.android.onetimeinitializer
#com.sec.android.widgetapp.digitalclock
#com.android.wallpapercropper
#com.samsung.android.provider.shootingmodeprovider
#com.sec.android.app.wfdbroker
#com.samsung.android.app.withtv
#com.skms.android.agent
#com.sec.android.app.safetyassurance
#com.sec.factory.camera
#org.simalliance.openmobileapi.service
#com.sec.usbsettings
#com.samsung.android.easysetup
#com.android.documentsui
#com.sec.android.app.SPenKeeper
#com.android.externalstorage
#com.sec.android.easyonehand
#com.sec.factory
#com.android.htmlviewer
#com.android.mms.service
#com.android.providers.downloads
#com.samsung.ucs.agent.boot
#com.wsomacp
#com.sec.android.app.FlashBarService
#com.sec.android.Kies
#com.sec.android.app.voicenote
#com.samsung.knox.rcp.components
#com.samsung.android.intelligenceservice2
#com.sec.di.SmartSelfShot
#com.samsung.android.MtpApplication
#com.sec.android.app.factorykeystring
#com.sec.android.app.samsungapps
#com.sec.android.emergencymode.service
#com.google.android.configupdater
#com.sec.android.app.wlantest
#com.sec.android.widgetapp.SPlannerAppWidget
#com.sec.android.app.minimode.res
#com.android.defcontainer
#com.sec.android.daemonapp
#com.sec.enterprise.knox.attestation
#com.android.vending
#com.android.pacprocessor
#com.sec.android.app.musiccontroller
#com.sec.android.app.popupuireceiver
#com.sec.android.AutoPreconfig
#com.sec.android.app.soundalive
#com.sec.android.providers.security
#com.sec.android.provider.badge
#com.android.certinstaller
#com.samsung.android.securitylogagent
#com.android.carrierconfig
#com.google.android.marvin.talkback
#com.sec.android.app.taskmanager
#com.samsung.android.app.assistantmenu
#com.samsung.SMT
#com.samsung.dcm
#com.sec.android.ofviewer
#com.samsung.everglades.video
#android
#com.android.contacts
#com.samsung.hs20provider
#com.samsung.android.sm.devicesecurity
#com.samsung.android.smartface
#com.android.mms
#com.android.nfc
#com.android.stk
#com.sec.knox.foldercontainer
#com.android.backupconfirm
#com.samsung.klmsagent
#com.sec.android.app.storycam
#com.sec.android.app.SecSetupWizard
#com.android.statementservice
#com.google.android.gm
#com.sec.android.app.hwmoduletest
#com.sec.bcservice
#com.sec.spen.flashannotate
#com.android.calendar
#com.sec.modem.settings
#com.android.phasebeam
#com.monotype.android.font.samsungsans
#com.sec.android.app.sysscope
#com.sec.android.app.wallpaperchooser
#com.samsung.android.providers.context
#com.sec.android.app.servicemodeapp
#com.sec.android.preloadinstaller
#com.google.android.setupwizard
#com.samsung.android.sdk.professionalaudio.utility.jammonitor
#com.sec.android.gallery3d
#com.sec.android.app.automotive.carmoderemote
#com.android.providers.settings
#com.qualcomm.qcom_qmi
#com.sec.app.TransmitPowerService
#com.android.sharedstoragebackup
#com.sec.android.widgetapp.dualclockdigital
#com.samsung.android.app.colorblind
#com.sec.providers.settingsearch

#com.sec.android.app.music
#com.android.incallui
#com.sec.android.omc
#com.sec.android.app.dictionary
#com.android.inputdevices
#com.sec.esdk.elm
#com.sec.android.app.videoplayer
#com.sec.android.app.filtermanager
#com.sec.android.service.sm
#com.sec.android.gallery3d.panorama360view
#com.sec.smartcard.manager
#com.sec.android.Preconfig
#com.sec.android.settingsmaps
#com.samsung.app.slowmotion
#com.google.android.apps.docs
#com.google.android.apps.maps
#com.sec.enterprise.mdm.vpn
#com.samsung.android.app.pinboard
#com.samsung.android.personalpage.service
#com.sec.android.inputmethod
#com.samsung.android.app.advsounddetector
#com.sec.android.app.clockpackage
#com.sec.android.RilServiceModeApp
#com.google.android.webview
#com.android.server.telecom
#com.google.android.syncadapters.contacts
#com.samsung.android.clipboarduiservice
#com.android.keychain
#com.samsung.android.asksmanager
#com.google.android.packageinstaller
#com.samsung.android.sm
#com.sec.android.widgetapp.locationwidget
#com.google.android.gms
#com.google.android.gsf
#com.google.android.tts
#com.android.calllogbackup
#com.google.android.partnersetup
#com.sec.android.diagmonagent
#com.sec.android.easysidepanel
#com.sec.spp.push
#com.sec.android.widgetapp.digitalclockeasy
#com.sec.android.app.myfiles
#com.android.proxyhandler
#com.sec.android.mimage.photoretouching
#com.sec.android.app.launcher
#com.sec.android.automotive.drivelink
#com.samsung.helphub
#com.sec.android.app.sns3
#com.google.android.syncadapters.calendar
#com.android.managedprovisioning
#com.samsung.android.app.filterinstaller
#com.hancom.office.viewer
#com.sec.android.providers.tasks
#com.sec.android.app.sbrowser
#com.lifevibes.trimapp

#com.sec.android.service.health
#com.samsung.safetyinformation
#com.sec.android.app.ringtoneBR
#com.android.noisefield
#com.android.providers.partnerbookmarks
#com.google.android.gsf.login
#com.cleanmaster.sdk
#com.samsung.android.keyguardwallpaperupdator
#com.samsung.android.app.accesscontrol
#com.android.wallpaper.livepicker
#com.samsung.android.beaconmanager
#com.sec.enterprise.mdm.services.simpin
#com.samsung.ucs.ucspinpad
#com.android.apps.tag
#com.samsung.android.app.FileShareClient
#com.sec.android.app.popupcalculator
#com.sec.android.soagent
#com.samsung.android.scloud.backup
#com.samsung.android.fmm
#com.samsung.android.mdm
#com.sec.android.app.shealth
#com.sec.phone
#com.samsung.android.app.scrollcapture
#com.samsung.knox.appsupdateagent
#com.google.android.backuptransport
#com.sec.knox.knoxsetupwizardclient
#com.visionobjects.resourcemanager
#com.samsung.android.scloud
#com.sec.app.RilErrorNotifier
#com.android.bookmarkprovider
#com.android.settings
#com.samsung.app.newtrim
#com.sec.android.mmapp
#com.sec.android.app.bluetoothtest
#com.samsung.android.intelligenceservice
#com.samsung.android.sm.policy
#com.sec.hearingadjust
#com.qualcomm.location
#com.samsung.android.bbc.bbcagent
#com.samsung.android.nearby.mediaserver
#com.sec.spen.flashannotatesvc
#com.sec.android.cloudagent
#com.wssnps
#com.samsung.android.app.watchmanagerstub
#com.sec.android.app.interactivekeyguardtutorial
#com.policydm
#com.sec.android.app.SmartClipService
#com.samsung.android.app.FileShareServer
#com.samsung.android.sdk.professionalaudio.app.audioconnectionservice
#com.samsung.android.service.aircommand
#com.enhance.gameservice
#com.sec.android.app.snsimagecache
#com.qualcomm.qti.services.secureui
#com.android.vpndialogs
#com.android.email
#com.android.phone
#com.android.shell
#com.android.providers.userdictionary
#com.sec.enterprise.knox.cloudmdm.smdms
#com.arcsoft.magicshotstudio
#com.wssyncmldm
#com.android.location.fused
#com.samsung.android.sm.provider
#com.sec.face
#com.android.systemui
#com.sec.android.app.personalization
#com.android.exchange
#com.android.bluetoothmidiservice
#com.sec.android.provider.logsprovider
#com.sec.android.app.SamsungContentsAgent
#com.samsung.aasaservice
#com.sec.android.app.mt
#com.sec.android.provider.emergencymode
#com.samsung.android.fingerprint.service
#com.sec.knox.switcher
#com.sec.android.app.camera
#com.samsung.android.tzdata.update_M
#com.android.bluetooth
#com.qualcomm.timeservice
#com.qualcomm.atfwd
#com.qualcomm.embms
#com.android.providers.contacts
#com.sec.android.app.magnifier
#com.samsung.sec.android.application.csc
#com.android.captiveportallogin
#com.sec.android.filter
#com.samsung.android.sconnect
#com.samsung.android.coreapps
#com.sec.android.easysettings
#com.samsung.android.snote
#com.samsung.location
#com.sec.android.mimage.sstudio
